# Generated by Django 4.2.23 on 2025-08-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_varaiacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varaiacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
